from typing import Literal

from pydantic import BaseModel, Field


class NarrationSegment(BaseModel):
    """One TTS-friendly chunk followed by an explicit pause."""

    text: str = Field(min_length=1, max_length=600)
    tts_text: str = Field(min_length=1, max_length=700)
    pause_after_ms: int = Field(default=350, ge=0, le=1500)


class NarrationPlan(BaseModel):
    """Validated narration plan generated by the LLM or fallback splitter."""

    title: str = "Український наратив"
    language: Literal["uk-UA"] = "uk-UA"
    segments: list[NarrationSegment] = Field(min_length=1, max_length=200)
